absl-py==1.2.0
aiohttp @ file:///tmp/build/80754af9/aiohttp_1646806365504/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
anyio==3.6.1
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///tmp/build/80754af9/argon2-cffi-bindings_1644569679365/work
astor==0.8.1
asttokens==2.0.8
astunparse==1.6.3
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
async-timeout==4.0.2
attrs==22.1.0
Babel==2.10.3
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///opt/conda/conda-bld/beautifulsoup4_1650462163268/work
bertopic==0.11.0
bleach==5.0.1
blinker==1.5
blis==0.7.8
Bottleneck @ file:///opt/conda/conda-bld/bottleneck_1657175564434/work
bpemb==0.3.3
brotlipy==0.7.0
cachetools==5.2.0
catalogue==2.0.8
certifi==2022.6.15
cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work
chardet==5.0.0
charset-normalizer==2.1.1
chart-studio==1.1.0
click==8.1.3
cloudpickle==2.1.0
colorama==0.4.5
commonmark==0.9.1
conllu==4.5.2
contextualized-topic-models==2.3.0
coverage==6.4.4
cryptography==37.0.4
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
cymem==2.0.6
Cython==0.29.32
daal==2021.6.0
daal4py==2021.6.3
de-core-news-lg @ https://github.com/explosion/spacy-models/releases/download/de_core_news_lg-3.2.0/de_core_news_lg-3.2.0-py3-none-any.whl
debugpy==1.6.3
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
Deprecated==1.2.13
deprecation==2.1.0
distro==1.7.0
docx2txt==0.8
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.4.0/en_core_web_lg-3.4.0-py3-none-any.whl
en-core-web-md @ https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.3.1/en_core_web_md-2.3.1.tar.gz
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl
entrypoints @ file:///tmp/build/80754af9/entrypoints_1649926439650/work
et-xmlfile==1.1.0
executing==1.0.0
eyed3==0.9.6
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1658064924516/work/dist
feedparser==6.0.10
filelock==3.8.0
filetype==1.1.0
flair==0.11.3
Flask==2.2.2
flatbuffers==1.12
fonttools==4.37.1
frozenlist==1.3.1
ftfy==6.1.1
funcy @ file:///home/conda/feedstock_root/build_artifacts/funcy_1640095670534/work
future @ file:///tmp/build/80754af9/future_1607571303524/work
gast==0.4.0
gdown==4.5.1
gensim==4.2.0
google-auth==2.11.0
google-auth-oauthlib==0.4.6
google-pasta @ file:///Users/ktietz/demo/mc3/conda-bld/google-pasta_1630577991354/work
grpcio==1.48.1
h11==0.13.0
h5py==3.7.0
hdbscan==0.8.28
huggingface-hub==0.9.1
hyperopt==0.2.7
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
importlib-metadata==4.12.0
influxdb-client==1.32.0
ipykernel==6.15.2
ipython==8.4.0
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==8.0.2
itsdangerous==2.1.2
Janome==0.4.2
jedi==0.17.2
Jinja2==3.1.2
joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
jovian==0.2.41
json5==0.9.10
jsonlines==3.1.0
jsonschema==4.15.0
jupyter @ file:///tmp/abs_33h4eoipez/croots/recipe/jupyter_1659349046347/work
jupyter-console==6.4.4
jupyter-contrib-core==0.4.0
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.11.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.5.0
jupyter-resource-usage==0.6.2
jupyter-server @ file:///tmp/abs_b88b31b8-83b9-476d-a46d-e563c421f38fvsnyi1ur/croots/recipe/jupyter_server_1658754481507/work
jupyter_client==7.3.5
jupyterlab==3.4.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
jupyterlab_server==2.15.1
jupyterthemes==0.20.0
kaleido==0.2.1
keras==2.9.0
Keras-Preprocessing @ file:///tmp/build/80754af9/keras-preprocessing_1612283640596/work
keybert==0.6.0
keyphrase-vectorizers==0.0.10
kiwisolver==1.4.4
konoha==5.3.0
langcodes==3.3.0
langdetect==1.0.9
lesscpy==0.15.0
libclang==14.0.6
libsvm==3.23.0.4
linkedin-jobs-scraper==1.15.4
llvmlite==0.39.1
lxml==4.9.1
Markdown==3.4.1
MarkupSafe @ file:///opt/conda/conda-bld/markupsafe_1654597864307/work
matplotlib==3.5.3
matplotlib-inline==0.1.6
mistune==2.0.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186066731/work
mkl-service==2.4.0
more-itertools==8.14.0
mpld3==0.5.8
multidict==6.0.2
munkres==1.1.4
murmurhash==1.0.8
mutagen==1.45.1
nbclassic==0.4.3
nbclient==0.6.7
nbconvert==7.0.0
nbformat==5.4.0
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1649847906199/work
networkx==2.8.6
nltk @ file:///opt/conda/conda-bld/nltk_1645628263994/work
notebook @ file:///tmp/abs_abf6xa6h6f/croots/recipe/notebook_1659083654985/work
notebook-shim==0.1.0
numba==0.56.2
numexpr @ file:///opt/conda/conda-bld/numexpr_1656940300424/work
numpy==1.23.2
oauthlib @ file:///tmp/abs_08ngfezid4/croots/recipe/oauthlib_1659642459222/work
octis==1.10.4
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
openpyxl==3.0.10
opt-einsum @ file:///tmp/build/80754af9/opt_einsum_1621500238896/work
outcome==1.2.0
overrides==6.2.0
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.4.4
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso==0.7.1
pathy==0.6.2
pdfminer.six==20220524
pdfplumber==0.7.4
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
phonenumbers==8.12.54
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.2.0
plac==1.3.5
plotly==5.10.0
ply==3.11
pptree==3.1
preshed==3.0.7
pretty-errors==1.2.25
prometheus-client @ file:///tmp/abs_d3zeliano1/croots/recipe/prometheus_client_1659455100375/work
prompt-toolkit==3.0.31
protobuf==3.19.4
psutil==5.9.1
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
py4j==0.10.9.7
pyaml==21.10.1
pyasn1 @ file:///Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/work
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pycryptodome==3.15.0
pydantic==1.9.2
pydub==0.25.1
Pygments==2.13.0
PyJWT @ file:///opt/conda/conda-bld/pyjwt_1657544592787/work
pyLDAvis @ file:///home/conda/feedstock_root/build_artifacts/pyldavis_1616598811607/work
pymongo==4.2.0
pynndescent==0.5.7
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.0.9
PyPDF2==2.10.4
PyQt5-sip==12.11.0
pyresparser==1.0.6
pyrsistent==0.18.1
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
pytesseract==0.3.10
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz==2022.2.1
PyYAML==5.4.1
pyzmq==23.2.1
qtconsole==5.3.2
QtPy==2.2.0
reactivex==4.0.4
regex==2022.8.17
requests @ file:///opt/conda/conda-bld/requests_1657734628632/work
requests-oauthlib==1.3.1
resume-parser==0.8.4
retrying==1.3.3
rich==12.5.1
rsa==4.9
Rx==3.2.0
sacremoses==0.0.53
scikit-learn==1.1.2
scikit-learn-intelex==2021.20220215.212715
scikit-optimize==0.9.0
scipy==1.9.1
seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work
segtok==1.5.11
selenium==4.4.3
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sentence-transformers==2.2.2
sentencepiece==0.1.97
sgmllib3k==1.0.0
sip @ file:///tmp/abs_44cd77b_pu/croots/recipe/sip_1659012365470/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sklearn==0.0
smart-open==5.2.1
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
spacy==3.4.1
spacy-alignments==0.8.5
spacy-legacy==3.0.10
spacy-loggers==1.0.3
spacy-transformers==1.1.8
sqlitedict==2.0.0
srsly==2.4.4
srt==3.5.2
stack-data==0.5.0
stemming==1.0.1
tabula-py==2.5.1
tabulate==0.8.10
tbb==2021.6.0
tenacity @ file:///tmp/abs_9ca5cd06-f53b-4ea6-8eea-954e11157fddo5mhurpp/croots/recipe/tenacity_1657899103026/work
termcolor==1.1.0
terminado==0.15.0
testpath @ file:///opt/conda/conda-bld/testpath_1655908557405/work
thinc==8.1.0
threadpoolctl==3.1.0
tika==1.24
tinycss2==1.1.1
tokenizers==0.12.1
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomotopy==0.12.3
tornado==6.2
tqdm==4.64.1
traitlets==5.3.0
transformers==4.21.2
trio==0.21.0
trio-websocket==0.9.2
typer==0.6.1
typing_extensions @ file:///tmp/abs_ben9emwtky/croots/recipe/typing_extensions_1659638822008/work
umap-learn==0.5.3
urllib3==1.26.12
uuid==1.30
vosk==0.3.43
Wand==0.6.10
wasabi==0.10.1
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client==1.4.0
websockets==10.3
Werkzeug==2.2.2
wget==3.2
widgetsnbextension==4.0.3
Wikipedia-API==0.5.4
windrose==1.7.0
wordcloud==1.8.2.2
wrapt @ file:///tmp/abs_c335821b-6e43-4504-9816-b1a52d3d3e1eel6uae8l/croots/recipe/wrapt_1657814400492/work
wsproto==1.2.0
yarl==1.8.1
zipp==3.8.1
